### ISSUE TITLE
Unable to install VAPIX

### ISSUE THREAD

**Issue by mnurme** [gluxon/node-vapix#2]
Unable to install VAPIX. Has something to do with buffertools.
Included npm-debug-log file.

[npm-debug.txt](https://github.com/gluxon/node-vapix/files/98004/npm-debug.txt)

**Comment by gluxon** [comment]
Should be fixed with latest update. Thanks for reporting.

**Comment by mnurme** [comment]
Thank You for the fast reply!
Unfortunately for me the same issue still persists. Installation still fails because of buffertools node-gyp rebuilt installation. Was vapix node.js API ment to be used with Windows?
As it turns out buffertools has no prebuild package for windows. People using emailjs and ldapjs have the same issue when installing their packages as they have buffertools dependancy as well.
I`m yet a node.js beginner and don`t know how to fix these issues myself.
Included another npm-debug-log file
[npm-debug.txt](https://github.com/gluxon/node-vapix/files/98870/npm-debug.txt)

**Comment by gluxon** [comment]
Do you have python and Visual Studio installed? buffertools is a native package that needs a small c compiler. Linux and OS X have the requirements builtin, but Windows will need a few prerequisites.

https://github.com/bnoordhuis/node-buffertools/issues/62
